from abjad.tools import datastructuretools
import mongoengine
import re
from discograph.models.Model import Model


class ArtistRole(Model, mongoengine.EmbeddedDocument):

    ### CLASS VARIABLES ###

    class Heading(datastructuretools.Enumeration):
        ACTING_LITERARY_AND_SPOKEN = 1
        CONDUCTING_AND_LEADING = 2
        DJ_MIX = 3
        FEATURING_AND_PRESENTING = 4
        INSTRUMENTS = 5
        MANAGEMENT = 6
        PRODUCTION = 7
        RELATION = 13
        REMIX = 8
        TECHNICAL = 9
        VISUAL = 10
        VOCAL = 11
        WRITING_AND_ARRANGEMENT = 12

    class Subheading(datastructuretools.Enumeration):
        DRUMS_AND_PERCUSSION = 1
        KEYBOARD = 2
        OTHER_MUSICAL = 3
        STRINGED_INSTRUMENTS = 4
        TECHNICAL_MUSICAL = 5
        TUNED_PERCUSSION = 6
        WIND_INSTRUMENTS = 7

    _bracket_pattern = re.compile('\[(.+?)\]')

    _available_credit_roles = {

        "Alias": (Heading.RELATION,),
        "Member Of": (Heading.RELATION,),
        "Released On": (Heading.RELATION,),
        "Split With": (Heading.RELATION,),
        "Collaborated With": (Heading.RELATION,),

        "Artwork By": None,
        "Executive Producer": None,
        "Other": None,
        "Photography": None,
        "Written By": None,

        "Adapted By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Arranged By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Cadenza": (Heading.WRITING_AND_ARRANGEMENT,),
        "Composed By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Concept By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Copyist": (Heading.WRITING_AND_ARRANGEMENT,),
        "Instrumentation By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Libretto By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Lyrics By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Music By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Music Consultant": (Heading.WRITING_AND_ARRANGEMENT,),
        "Musical Assistance": (Heading.WRITING_AND_ARRANGEMENT,),
        "Orchestrated By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Programmed By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Score Editor": (Heading.WRITING_AND_ARRANGEMENT,),
        "Score": (Heading.WRITING_AND_ARRANGEMENT,),
        "Sequenced By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Songwriter": (Heading.WRITING_AND_ARRANGEMENT,),
        "Sound Designer": (Heading.WRITING_AND_ARRANGEMENT,),
        "Transcription By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Translated By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Words By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Written-By": (Heading.WRITING_AND_ARRANGEMENT,),

        "Featuring": (Heading.FEATURING_AND_PRESENTING),
        "Hosted By": (Heading.FEATURING_AND_PRESENTING,),
        "Presenter": (Heading.FEATURING_AND_PRESENTING,),

        "Chorus Master": (Heading.CONDUCTING_AND_LEADING,),
        "Concertmaster": (Heading.CONDUCTING_AND_LEADING,),
        "Concertmistress": (Heading.CONDUCTING_AND_LEADING,),
        "Conductor": (Heading.CONDUCTING_AND_LEADING,),
        "Contractor": (Heading.CONDUCTING_AND_LEADING,),
        "Directed By": (Heading.CONDUCTING_AND_LEADING,),
        "Leader": (Heading.CONDUCTING_AND_LEADING,),
        "Repetiteur": (Heading.CONDUCTING_AND_LEADING,),

        "Co-producer": (Heading.PRODUCTION,),
        "Commissioned By": (Heading.PRODUCTION,),
        "Compilation Producer": (Heading.PRODUCTION,),
        "Compiled By": (Heading.PRODUCTION,),
        "Curated By": (Heading.PRODUCTION,),
        "Executive-Producer": (Heading.PRODUCTION,),
        "Producer": (Heading.PRODUCTION,),
        "Recording Supervisor": (Heading.PRODUCTION,),
        "Reissue Producer": (Heading.PRODUCTION,),
        "Research": (Heading.PRODUCTION,),
        "Supervised By": (Heading.PRODUCTION,),

        "Remix": (Heading.REMIX,),

        "DJ Mix": (Heading.DJ_MIX,),

        "Animation": (Heading.VISUAL,),
        "Artwork": (Heading.VISUAL,),
        "Assemblage": (Heading.VISUAL,),
        "Art Direction": (Heading.VISUAL,),
        "Cameraman": (Heading.VISUAL,),
        "CGI Artist": (Heading.VISUAL,),
        "Cinematographer": (Heading.VISUAL,),
        "Cover": (Heading.VISUAL,),
        "Creative Director": (Heading.VISUAL,),
        "Design Concept": (Heading.VISUAL,),
        "Design": (Heading.VISUAL,),
        "Director Of Photography": (Heading.VISUAL,),
        "Film Director": (Heading.VISUAL,),
        "Film Editor": (Heading.VISUAL,),
        "Film Producer": (Heading.VISUAL,),
        "Film Technician": (Heading.VISUAL,),
        "Gaffer": (Heading.VISUAL,),
        "Graphics": (Heading.VISUAL,),
        "Grip": (Heading.VISUAL,),
        "Illustration": (Heading.VISUAL,),
        "Layout": (Heading.VISUAL,),
        "Lighting Director": (Heading.VISUAL,),
        "Lighting": (Heading.VISUAL,),
        "Painting": (Heading.VISUAL,),
        "Photography By": (Heading.VISUAL,),
        "Production Manager": (Heading.VISUAL,),
        "Realization": (Heading.VISUAL,),
        "Set Designer": (Heading.VISUAL,),
        "Sleeve": (Heading.VISUAL,),
        "Stage Manager": (Heading.VISUAL,),
        "Typography": (Heading.VISUAL,),
        "Video Editor": (Heading.VISUAL,),
        "VJ": (Heading.VISUAL,),

        "Abridged By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Adapted By (Text)": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Choreography": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewee": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewer": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Liner Notes": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Music Librarian": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Narrator": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Read By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Screenwriter": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Script By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Sleeve Notes": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Text By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Voice Actor": (Heading.ACTING_LITERARY_AND_SPOKEN,),

        "A\u0026R": (Heading.MANAGEMENT,),
        "Administrator": (Heading.MANAGEMENT,),
        "Advisor": (Heading.MANAGEMENT,),
        "Booking": (Heading.MANAGEMENT,),
        "Coordinator": (Heading.MANAGEMENT,),
        "Legal": (Heading.MANAGEMENT,),
        "Management": (Heading.MANAGEMENT,),
        "Product Manager": (Heading.MANAGEMENT,),

        "Crew": (Heading.TECHNICAL,),
        "DAW": (Heading.TECHNICAL,),
        "Edited By": (Heading.TECHNICAL,),
        "Engineer": (Heading.TECHNICAL,),
        "Lacquer Cut By": (Heading.TECHNICAL,),
        "Mastered By": (Heading.TECHNICAL,),
        "Mixed By": (Heading.TECHNICAL,),
        "Recorded By": (Heading.TECHNICAL,),
        "Remastered By": (Heading.TECHNICAL,),
        "Tape Op": (Heading.TECHNICAL,),
        "Technician": (Heading.TECHNICAL,),
        "Tracking By": (Heading.TECHNICAL,),
        "Transferred By": (Heading.TECHNICAL,),

        "Alto Vocals": (Heading.VOCAL,),
        "Backing Vocals": (Heading.VOCAL,),
        "Baritone Vocals": (Heading.VOCAL,),
        "Bass Vocals": (Heading.VOCAL,),
        "Caller": (Heading.VOCAL,),
        "Choir": (Heading.VOCAL,),
        "Chorus": (Heading.VOCAL,),
        "Contralto Vocals": (Heading.VOCAL,),
        "Coro": (Heading.VOCAL,),
        "Countertenor Vocals": (Heading.VOCAL,),
        "Harmony Vocals": (Heading.VOCAL,),
        "Human Beatbox": (Heading.VOCAL,),
        "Humming": (Heading.VOCAL,),
        "Kakegoe": (Heading.VOCAL,),
        "Lead Vocals": (Heading.VOCAL,),
        "MC": (Heading.VOCAL,),
        "Mezzo-soprano Vocals": (Heading.VOCAL,),
        "Overtone Voice": (Heading.VOCAL,),
        "Rap": (Heading.VOCAL,),
        "Scat": (Heading.VOCAL,),
        "Solo Vocal": (Heading.VOCAL,),
        "Soprano Vocals": (Heading.VOCAL,),
        "Speech": (Heading.VOCAL,),
        "Tenor Vocals": (Heading.VOCAL,),
        "Toasting": (Heading.VOCAL,),
        "Treble Vocals": (Heading.VOCAL,),
        "Vocalese": (Heading.VOCAL,),
        "Vocals": (Heading.VOCAL,),
        "Voice": (Heading.VOCAL,),
        "Whistling": (Heading.VOCAL,),
        "Yodeling": (Heading.VOCAL,),

        "Afox\u00e9": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Agog\u00f4": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ashiko": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bapang": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bass Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bata": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bell Tree": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bells": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bendir": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bodhr\u00e1n": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Body Percussion": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bombo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bones": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bongos": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Buhay": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Buk": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cabasa": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caixa": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caj\u00f3n": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Calabash": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Castanets": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caxixi": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Chak\u0027chas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ching": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Claves": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Congas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cowbell": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cuica": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cymbal": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Daf": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Davul": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dhol": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dholak": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Djembe": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drum Programming": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drums": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dunun": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Electronic Drums": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Finger Cymbals": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Finger Snaps": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Frame Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Friction Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ganz\u00e1": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ghatam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ghungroo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Goblet Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Gong": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Handclaps": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Hihat": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Idiophone": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Janggu": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "K\u0027kwaengwari": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Kanjira": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Karkabas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Khartal": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Khurdak": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Lion\u0027s Roar": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Maracas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Monkey stick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Mridangam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Pandeiro": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Percussion": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rainstick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ratchet": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rattle": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Reco-reco": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Repinique": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rototoms": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Scraper": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Shaker": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Shekere": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Singing Bowls": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Skratjie": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Slapstick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Slit Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Snare": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Spoons": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Surdo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tabla": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Taiko": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Talking Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tam-tam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tambora": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tamborim": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tambourine": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tan-Tan": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tap Dance": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tar (Drum)": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "T\u00fcng\u00fcr": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Temple Bells": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Temple Block": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Timbales": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Timpani": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tom Tom": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Triangle": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Udu": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Vibraslap": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Washboard": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Wood Block": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),

        "Amadinda": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Angklung": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Angklung": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Boomwhacker": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Carillon": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Celesta": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Chimes": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Crotales": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Glockenspiel": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Kalimba": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Marimba": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Marimbula": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Metallophone": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Musical Box": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Steel Drums": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Thumb Piano": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Vibraphone": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),
        "Xylophone": (Heading.INSTRUMENTS, Subheading.TUNED_PERCUSSION),

        "Baby Grand Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Chamberlin": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Concert Grand Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Dulcitone": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Electric Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Fortepiano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Grand Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Harmonium": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Harpsichord": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Keyboards": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Mellotron": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Melodica": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Omnichord": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Ondes Martenot": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Organ": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Parlour Grand Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Pedalboard": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Player Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Regal": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Stylophone": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Synth": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Synthesizer": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Toy Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Upright Piano": (Heading.INSTRUMENTS, Subheading.KEYBOARD),
        "Virginal": (Heading.INSTRUMENTS, Subheading.KEYBOARD),

        "Acoustic Bass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Acoustic Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Arco Bass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Arpa": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Autoharp": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Baglama": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bajo Quinto": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bajo Sexto": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Balalaika": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bandura": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bandurria": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Banhu": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Banjo": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Baritone Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bass Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Berimbau": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bhapang": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Biwa": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Blaster Beam": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bouzouki": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Bulbul Tarang": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Byzaanchi": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "C\u00fcmb\u00fc\u015f": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cavaquinho": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cello": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Chanzy": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Chapman Stick": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Charango": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Chitarrone": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cimbalom": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cittern": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Classical Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Clavichord": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Clavinet": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cobza": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Contrabass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Cuatro": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Dilruba": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Domra": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Doshpuluur": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Double Bass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Dulcimer": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Dutar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Ehru": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Ektare": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Electric Bass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Electric Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Electric Upright Bass": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Erhu": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Esraj": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Fiddle": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Flamenco Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Gadulka": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Gaohu": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Gayageum": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Geomungo": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Gottuv\u00e2dyam": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guimbri": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guitalele": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guitar Synthesizer": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "GuitarViol": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guitarr\u00f3n": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guqin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Gusli": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Guzheng": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Hardingfele": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Harp Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Harp": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Hummel": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Huqin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Hurdy Gurdy": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Igil": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Jarana": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Jouhikko": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kabosy": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kamancha": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kantele": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kanun": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kemenche": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kobyz": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kokyu": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Kora": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Koto": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "La\u00fad": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Lap Steel Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Lead Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Liuqin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Lute": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Lyre": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Mandocello": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Mandoguitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Mandola": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Mandolin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Mandolincello": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Monochord": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Morinhoor": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Musical bow": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Nyckelharpa": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Oud": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Outi": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Pedal Steel Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Pipa": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Portuguese Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Psalmodicon": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Psaltery": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Rabab": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Rebab": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Rebec": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Requinto Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Resonator Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Rhythm Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Ruan": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Santoor": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sanxian": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sarangi": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sarod": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Semi-Acoustic Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Shahi Baaja": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Shamisen": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sintir": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Slide Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Spinet": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Steel Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Strings": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Stroh Violin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Strumstick": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Surbahar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Svara Mandala": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Swarmandel": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Sympitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "SynthAxe": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tambura": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tamburitza": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tapboard": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tar (lute)": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Theorbo": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tiple": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tipple": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tonkori": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Tres": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Twelve-String Guitar": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Ukulele": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Utogardon": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Valiha": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Veena": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Vielle": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Vihuela": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Viol": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Viola d\u0027Amore": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Viola": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Violin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Violone": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Xalam": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Yang T\u0027Chin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Yangqin": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Zither": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "Zongora": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),
        "\u0110\u00e0n b\u1ea7u": (Heading.INSTRUMENTS, Subheading.STRINGED_INSTRUMENTS),

        "Accordion": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Algoza": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Alphorn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Alto Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Alto Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Alto Recorder": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Alto Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Apito": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bagpipes": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bandoneon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bansuri": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Baritone Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Barrel Organ": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bass Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bass Harmonica": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bass Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bass Tuba": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Basset Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bassoon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bayan": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bellowphone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Beresta": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Blues Harp": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bombarde": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Brass Bass": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Brass": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bucium": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Bugle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Chalumeau": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Chanter": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Chirimia": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Clarion": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Claviola": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Concert Flute": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Concertina": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Conch": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Contra-Alto Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Contrabass Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Contrabass Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Contrabassoon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Cor Anglais": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Cornet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Cornett": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Crumhorn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Daegeum": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Didgeridoo": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Dili Tuiduk": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Dizi": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Drone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Duduk": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Dulcian": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Dulzaina": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Electronic Valve Instrument": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Electronic Wind Instrument": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "English Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Euphonium": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Fife": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Flageolet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Flugabone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Flugelhorn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Fluier": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Flute": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "French Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Gemshorn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Harmonica": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Heckelphone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Helicon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Horagai": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Horns": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Hunting Horn": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Jug": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Kaval": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Kazoo": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Khene": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Launeddas": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Low Whistle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Low Whistle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Lur": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Lur": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Lyricon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Lyricon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Mellophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Melodeon": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Mizmar": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Mizwad": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Moce\u00f1o": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Murli": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Musette": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Nadaswaram": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Ney": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Nose Flute": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Oboe d\u0027Amore": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Oboe": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Ocarina": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Ophicleide": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Panpipes": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Piano Accordion": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Piccolo Flute": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Pipe": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Pito": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Pixiephone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Quena": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Quenacho": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Rauschpfeife": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Recorder": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Reeds": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Rhaita": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Rondador": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Rozhok": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Ryuteki": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sackbut": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sampona": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sarrusophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Saxello": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Serpent": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Shakuhachi": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Shanai": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Shawm": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Shenai": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sheng": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Shinobue": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sho": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Slide Whistle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sopilka": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sopranino Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Soprano Clarinet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Soprano Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Souna": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sousaphone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Sruti Box": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Subcontrabass Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Suling": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Suona": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "T\u00e1rogat\u00f3": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Tenor Saxophone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Ti-tse": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Tin Whistle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Trombone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Trumpet": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Tuba": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Valve Trombone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Whistle": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Whistling Water Jar": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Wind": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Woodwind": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Yorgaphone": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Zhaleika": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Zukra": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),
        "Zurna": (Heading.INSTRUMENTS, Subheading.WIND_INSTRUMENTS),

        "Computer": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Drum Machine": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Effects": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Groovebox": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Loops": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "MIDI Controller": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Noises": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Sampler": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Scratches": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Talkbox": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Tape": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Theremin": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Turntables": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),
        "Vocoder": (Heading.INSTRUMENTS, Subheading.TECHNICAL_MUSICAL),

        "Accompanied By": (),
        "Audio Generator": (),
        "Backing Band": (),
        "Balafon": (),
        "Band": (),
        "Bass": (),
        "Brass Band": (),
        "Bullroarer": (),
        "Concert Band": (),
        "E-Bow": (),
        "Electronics": (),
        "Ensemble": (),
        "Gamelan": (),
        "Glass Harmonica": (),
        "Guest": (),
        "Guiro": (),
        "Halldorophone": (),
        "Homus": (),
        "Instruments": (),
        "Jew\u0027s Harp": (),
        "Jinghu": (),
        "Mbira": (),
        "Morchang": (),
        "Musician": (),
        "Orchestra": (),
        "Performer": (),
        "Ronroco": (),
        "Saw": (),
        "Siren": (),
        "Soloist": (),
        "Sounds": (),
        "Toy": (),
        "Trautonium": (),
        "Waterphone": (),
        "Wind Chimes": (),
        "Wobble Board": (),

        }

    ### MONGOENGINE FIELDS ###

    name = mongoengine.StringField()
    detail = mongoengine.StringField()

    ### PUBLIC METHODS ###

    @classmethod
    def from_element(cls, element):
        artist_roles = []
        if element is None or not element.text:
            return artist_roles
        current_text = ''
        bracket_depth = 0
        for character in element.text:
            if character == '[':
                bracket_depth += 1
            elif character == ']':
                bracket_depth -= 1
            elif not bracket_depth and character == ',':
                current_text = current_text.strip()
                if current_text:
                    artist_roles.append(cls.from_text(current_text))
                current_text = ''
                continue
            current_text += character
        current_text = current_text.strip()
        if current_text:
            artist_roles.append(cls.from_text(current_text))
        return artist_roles

    @classmethod
    def from_text(cls, text):
        name = ''
        current_buffer = ''
        details = []
        had_detail = False
        bracket_depth = 0
        for character in text:
            if character == '[':
                bracket_depth += 1
                if bracket_depth == 1 and not had_detail:
                    name = current_buffer
                    current_buffer = ''
                    had_detail = True
                elif 1 < bracket_depth:
                    current_buffer += character
            elif character == ']':
                bracket_depth -= 1
                if not bracket_depth:
                    details.append(current_buffer)
                    current_buffer = ''
                else:
                    current_buffer += character
            else:
                current_buffer += character
        if current_buffer and not had_detail:
            name = current_buffer
        name = name.strip()
        detail = ', '.join(_.strip() for _ in details)
        detail = detail or None
        return cls(name=name, detail=detail)