from abjad.tools import datastructuretools
import mongoengine
import re
from discograph.models.Model import Model


class ArtistRole(Model, mongoengine.EmbeddedDocument):

    ### CLASS VARIABLES ###

    class Heading(datastructuretools.Enumeration):
        ACTING_LITERARY_AND_SPOKEN = 1
        CONDUCTING_AND_LEADING = 2
        DJ_MIX = 3
        FEATURING_AND_PRESENTING = 4
        INSTRUMENTS = 5
        MANAGEMENT = 6
        PRODUCTION = 7
        RELATION = 13
        REMIX = 8
        TECHNICAL = 9
        VISUAL = 10
        VOCAL = 11
        WRITING_AND_ARRANGEMENT = 12

    class Subheading(datastructuretools.Enumeration):
        DRUMS_AND_PERCUSSION = 1
        KEYBOARD = 2
        OTHER_MUSICAL = 3
        STRINGED_INSTRUMENTS = 4
        TECHNICAL_MUSICAL = 5
        TUNED_PERCUSSION = 6
        WIND_INSTRUMENTS = 7

    _bracket_pattern = re.compile('\[(.+?)\]')

    _available_credit_roles = {

        "Alias": (Heading.RELATION,),
        "Member Of": (Heading.RELATION,),
        "Released On": (Heading.RELATION,),
        "Split With": (Heading.RELATION,),
        "Collaborated With": (Heading.RELATION,),

        "Artwork By": None,
        "Executive Producer": None,
        "Other": None,
        "Photography": None,
        "Written By": None,

        "Adapted By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Arranged By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Cadenza": (Heading.WRITING_AND_ARRANGEMENT,),
        "Composed By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Concept By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Copyist": (Heading.WRITING_AND_ARRANGEMENT,),
        "Instrumentation By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Libretto By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Lyrics By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Music By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Music Consultant": (Heading.WRITING_AND_ARRANGEMENT,),
        "Musical Assistance": (Heading.WRITING_AND_ARRANGEMENT,),
        "Orchestrated By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Programmed By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Score Editor": (Heading.WRITING_AND_ARRANGEMENT,),
        "Score": (Heading.WRITING_AND_ARRANGEMENT,),
        "Sequenced By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Songwriter": (Heading.WRITING_AND_ARRANGEMENT,),
        "Sound Designer": (Heading.WRITING_AND_ARRANGEMENT,),
        "Transcription By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Translated By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Words By": (Heading.WRITING_AND_ARRANGEMENT,),
        "Written-By": (Heading.WRITING_AND_ARRANGEMENT,),

        "Featuring": (Heading.FEATURING_AND_PRESENTING),
        "Hosted By": (Heading.FEATURING_AND_PRESENTING,),
        "Presenter": (Heading.FEATURING_AND_PRESENTING,),

        "Chorus Master": (Heading.CONDUCTING_AND_LEADING,),
        "Concertmaster": (Heading.CONDUCTING_AND_LEADING,),
        "Concertmistress": (Heading.CONDUCTING_AND_LEADING,),
        "Conductor": (Heading.CONDUCTING_AND_LEADING,),
        "Contractor": (Heading.CONDUCTING_AND_LEADING,),
        "Directed By": (Heading.CONDUCTING_AND_LEADING,),
        "Leader": (Heading.CONDUCTING_AND_LEADING,),
        "Repetiteur": (Heading.CONDUCTING_AND_LEADING,),

        "Co-producer": (Heading.PRODUCTION,),
        "Commissioned By": (Heading.PRODUCTION,),
        "Compilation Producer": (Heading.PRODUCTION,),
        "Compiled By": (Heading.PRODUCTION,),
        "Curated By": (Heading.PRODUCTION,),
        "Executive-Producer": (Heading.PRODUCTION,),
        "Producer": (Heading.PRODUCTION,),
        "Recording Supervisor": (Heading.PRODUCTION,),
        "Reissue Producer": (Heading.PRODUCTION,),
        "Research": (Heading.PRODUCTION,),
        "Supervised By": (Heading.PRODUCTION,),

        "Remix": (Heading.REMIX,),

        "DJ Mix": (Heading.DJ_MIX,),

        "Animation": (Heading.VISUAL,),
        "Artwork": (Heading.VISUAL,),
        "Assemblage": (Heading.VISUAL,),
        "Art Direction": (Heading.VISUAL,),
        "Cameraman": (Heading.VISUAL,),
        "CGI Artist": (Heading.VISUAL,),
        "Cinematographer": (Heading.VISUAL,),
        "Cover": (Heading.VISUAL,),
        "Creative Director": (Heading.VISUAL,),
        "Design Concept": (Heading.VISUAL,),
        "Design": (Heading.VISUAL,),
        "Director Of Photography": (Heading.VISUAL,),
        "Film Director": (Heading.VISUAL,),
        "Film Editor": (Heading.VISUAL,),
        "Film Producer": (Heading.VISUAL,),
        "Film Technician": (Heading.VISUAL,),
        "Gaffer": (Heading.VISUAL,),
        "Graphics": (Heading.VISUAL,),
        "Grip": (Heading.VISUAL,),
        "Illustration": (Heading.VISUAL,),
        "Layout": (Heading.VISUAL,),
        "Lighting Director": (Heading.VISUAL,),
        "Lighting": (Heading.VISUAL,),
        "Painting": (Heading.VISUAL,),
        "Photography By": (Heading.VISUAL,),
        "Production Manager": (Heading.VISUAL,),
        "Realization": (Heading.VISUAL,),
        "Set Designer": (Heading.VISUAL,),
        "Sleeve": (Heading.VISUAL,),
        "Stage Manager": (Heading.VISUAL,),
        "Typography": (Heading.VISUAL,),
        "Video Editor": (Heading.VISUAL,),
        "VJ": (Heading.VISUAL,),

        "Abridged By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Adapted By (Text)": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Choreography": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewee": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewer": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Liner Notes": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Music Librarian": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Narrator": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Read By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Screenwriter": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Script By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Sleeve Notes": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Text By": (Heading.ACTING_LITERARY_AND_SPOKEN,),
        "Voice Actor": (Heading.ACTING_LITERARY_AND_SPOKEN,),

        "A\u0026R": (Heading.MANAGEMENT,),
        "Administrator": (Heading.MANAGEMENT,),
        "Advisor": (Heading.MANAGEMENT,),
        "Booking": (Heading.MANAGEMENT,),
        "Coordinator": (Heading.MANAGEMENT,),
        "Legal": (Heading.MANAGEMENT,),
        "Management": (Heading.MANAGEMENT,),
        "Product Manager": (Heading.MANAGEMENT,),

        "Crew": (Heading.TECHNICAL,),
        "DAW": (Heading.TECHNICAL,),
        "Edited By": (Heading.TECHNICAL,),
        "Engineer": (Heading.TECHNICAL,),
        "Lacquer Cut By": (Heading.TECHNICAL,),
        "Mastered By": (Heading.TECHNICAL,),
        "Mixed By": (Heading.TECHNICAL,),
        "Recorded By": (Heading.TECHNICAL,),
        "Remastered By": (Heading.TECHNICAL,),
        "Tape Op": (Heading.TECHNICAL,),
        "Technician": (Heading.TECHNICAL,),
        "Tracking By": (Heading.TECHNICAL,),
        "Transferred By": (Heading.TECHNICAL,),

        "Alto Vocals": (Heading.VOCAL,),
        "Backing Vocals": (Heading.VOCAL,),
        "Baritone Vocals": (Heading.VOCAL,),
        "Bass Vocals": (Heading.VOCAL,),
        "Caller": (Heading.VOCAL,),
        "Choir": (Heading.VOCAL,),
        "Chorus": (Heading.VOCAL,),
        "Contralto Vocals": (Heading.VOCAL,),
        "Coro": (Heading.VOCAL,),
        "Countertenor Vocals": (Heading.VOCAL,),
        "Harmony Vocals": (Heading.VOCAL,),
        "Human Beatbox": (Heading.VOCAL,),
        "Humming": (Heading.VOCAL,),
        "Kakegoe": (Heading.VOCAL,),
        "Lead Vocals": (Heading.VOCAL,),
        "MC": (Heading.VOCAL,),
        "Mezzo-soprano Vocals": (Heading.VOCAL,),
        "Overtone Voice": (Heading.VOCAL,),
        "Rap": (Heading.VOCAL,),
        "Scat": (Heading.VOCAL,),
        "Solo Vocal": (Heading.VOCAL,),
        "Soprano Vocals": (Heading.VOCAL,),
        "Speech": (Heading.VOCAL,),
        "Tenor Vocals": (Heading.VOCAL,),
        "Toasting": (Heading.VOCAL,),
        "Treble Vocals": (Heading.VOCAL,),
        "Vocalese": (Heading.VOCAL,),
        "Vocals": (Heading.VOCAL,),
        "Voice": (Heading.VOCAL,),
        "Whistling": (Heading.VOCAL,),
        "Yodeling": (Heading.VOCAL,),

        "Afox\u00e9": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Agog\u00f4": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ashiko": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bapang": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bass Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bata": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bell Tree": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bells": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bendir": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bodhr\u00e1n": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Body Percussion": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bombo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bones": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Bongos": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Buhay": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Buk": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cabasa": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caixa": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caj\u00f3n": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Calabash": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Castanets": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Caxixi": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Chak\u0027chas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ching": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Claves": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Congas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cowbell": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cuica": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Cymbal": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Daf": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Davul": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dhol": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dholak": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Djembe": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drum Programming": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Drums": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Dunun": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Electronic Drums": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Finger Cymbals": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Finger Snaps": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Frame Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Friction Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ganz\u00e1": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ghatam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ghungroo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Goblet Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Gong": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Handclaps": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Hihat": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Idiophone": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Janggu": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "K\u0027kwaengwari": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Kanjira": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Karkabas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Khartal": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Khurdak": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Lion\u0027s Roar": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Maracas": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Monkey stick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Mridangam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Pandeiro": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Percussion": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rainstick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Ratchet": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rattle": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Reco-reco": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Repinique": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Rototoms": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Scraper": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Shaker": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Shekere": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Singing Bowls": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Skratjie": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Slapstick": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Slit Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Snare": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Spoons": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Surdo": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tabla": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Taiko": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Talking Drum": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tam-tam": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tambora": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tamborim": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tambourine": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tan-Tan": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tap Dance": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tar (Drum)": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "T\u00fcng\u00fcr": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Temple Bells": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Temple Block": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Timbales": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Timpani": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Tom Tom": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Triangle": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Udu": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Vibraslap": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Washboard": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),
        "Wood Block": (Heading.INSTRUMENTS, Subheading.DRUMS_AND_PERCUSSION),

        "Accompanied By": (),
        "Accordion": (),
        "Acoustic Bass": (),
        "Acoustic Guitar": (),
        "Algoza": (),
        "Alphorn": (),
        "Alto Clarinet": (),
        "Alto Horn": (),
        "Alto Recorder": (),
        "Alto Saxophone": (),
        "Amadinda": (),
        "Angklung": (),
        "Apito": (),
        "Arco Bass": (),
        "Arpa": (),
        "Audio Generator": (),
        "Autoharp": (),
        "Baby Grand Piano": (),
        "Backing Band": (),
        "Baglama": (),
        "Bagpipes": (),
        "Bajo Quinto": (),
        "Bajo Sexto": (),
        "Balafon": (),
        "Balalaika": (),
        "Band": (),
        "Bandoneon": (),
        "Bandura": (),
        "Bandurria": (),
        "Banhu": (),
        "Banjo": (),
        "Bansuri": (),
        "Baritone Guitar": (),
        "Baritone Saxophone": (),
        "Barrel Organ": (),
        "Bass Clarinet": (),
        "Bass Guitar": (),
        "Bass Harmonica": (),
        "Bass Saxophone": (),
        "Bass Tuba": (),
        "Bass": (),
        "Basset Horn": (),
        "Bassoon": (),
        "Bayan": (),
        "Bellowphone": (),
        "Beresta": (),
        "Berimbau": (),
        "Bhapang": (),
        "Biwa": (),
        "Blaster Beam": (),
        "Blues Harp": (),
        "Bombarde": (),
        "Boomwhacker": (),
        "Bouzouki": (),
        "Brass Band": (),
        "Brass Bass": (),
        "Brass": (),
        "Bucium": (),
        "Bugle": (),
        "Bulbul Tarang": (),
        "Bullroarer": (),
        "Byzaanchi": (),
        "C\u00fcmb\u00fc\u015f": (),
        "Carillon": (),
        "Cavaquinho": (),
        "Celesta": (),
        "Cello": (),
        "Chalumeau": (),
        "Chamberlin": (),
        "Chanter": (),
        "Chanzy": (),
        "Chapman Stick": (),
        "Charango": (),
        "Chimes": (),
        "Chirimia": (),
        "Chitarrone": (),
        "Cimbalom": (),
        "Cittern": (),
        "Clarinet": (),
        "Clarion": (),
        "Classical Guitar": (),
        "Clavichord": (),
        "Clavinet": (),
        "Claviola": (),
        "Cobza": (),
        "Computer": (),
        "Concert Band": (),
        "Concert Flute": (),
        "Concert Grand Piano": (),
        "Concertina": (),
        "Conch": (),
        "Contra-Alto Clarinet": (),
        "Contrabass Clarinet": (),
        "Contrabass Saxophone": (),
        "Contrabass": (),
        "Contrabassoon": (),
        "Cor Anglais": (),
        "Cornet": (),
        "Cornett": (),
        "Crotales": (),
        "Crumhorn": (),
        "Cuatro": (),
        "Daegeum": (),
        "Didgeridoo": (),
        "Dili Tuiduk": (),
        "Dilruba": (),
        "Dizi": (),
        "Domra": (),
        "Doshpuluur": (),
        "Double Bass": (),
        "Drone": (),
        "Drum Machine": (),
        "Duduk": (),
        "Dulcian": (),
        "Dulcimer": (),
        "Dulcitone": (),
        "Dulzaina": (),
        "Dutar": (),
        "E-Bow": (),
        "Effects": (),
        "Ehru": (),
        "Ektare": (),
        "Electric Bass": (),
        "Electric Guitar": (),
        "Electric Piano": (),
        "Electric Upright Bass": (),
        "Electronic Valve Instrument": (),
        "Electronic Wind Instrument": (),
        "Electronics": (),
        "English Horn": (),
        "Ensemble": (),
        "Erhu": (),
        "Esraj": (),
        "Euphonium": (),
        "Fiddle": (),
        "Fife": (),
        "Flageolet": (),
        "Flamenco Guitar": (),
        "Flugabone": (),
        "Flugelhorn": (),
        "Fluier": (),
        "Flute": (),
        "Fortepiano": (),
        "French Horn": (),
        "Gadulka": (),
        "Gamelan": (),
        "Gaohu": (),
        "Gayageum": (),
        "Gemshorn": (),
        "Geomungo": (),
        "Glass Harmonica": (),
        "Glockenspiel": (),
        "Gottuv\u00e2dyam": (),
        "Grand Piano": (),
        "Groovebox": (),
        "Guest": (),
        "Guimbri": (),
        "Guiro": (),
        "Guitalele": (),
        "Guitar Synthesizer": (),
        "Guitar": (),
        "GuitarViol": (),
        "Guitarr\u00f3n": (),
        "Guqin": (),
        "Gusli": (),
        "Guzheng": (),
        "Halldorophone": (),
        "Hardingfele": (),
        "Harmonica": (),
        "Harmonium": (),
        "Harp Guitar": (),
        "Harp": (),
        "Harpsichord": (),
        "Heckelphone": (),
        "Helicon": (),
        "Homus": (),
        "Horagai": (),
        "Horn": (),
        "Horns": (),
        "Hummel": (),
        "Hunting Horn": (),
        "Huqin": (),
        "Hurdy Gurdy": (),
        "Igil": (),
        "Instruments": (),
        "Jarana": (),
        "Jew\u0027s Harp": (),
        "Jinghu": (),
        "Jouhikko": (),
        "Jug": (),
        "Kabosy": (),
        "Kalimba": (),
        "Kamancha": (),
        "Kantele": (),
        "Kanun": (),
        "Kaval": (),
        "Kazoo": (),
        "Kemenche": (),
        "Keyboards": (),
        "Khene": (),
        "Kobyz": (),
        "Kokyu": (),
        "Kora": (),
        "Koto": (),
        "La\u00fad": (),
        "Lap Steel Guitar": (),
        "Launeddas": (),
        "Lead Guitar": (),
        "Liuqin": (),
        "Loops": (),
        "Low Whistle": (),
        "Lur": (),
        "Lute": (),
        "Lyre": (),
        "Lyricon": (),
        "MIDI Controller": (),
        "Mandocello": (),
        "Mandoguitar": (),
        "Mandola": (),
        "Mandolin": (),
        "Mandolincello": (),
        "Marimba": (),
        "Marimbula": (),
        "Mbira": (),
        "Mellophone": (),
        "Mellotron": (),
        "Melodeon": (),
        "Melodica": (),
        "Metallophone": (),
        "Mizmar": (),
        "Mizwad": (),
        "Moce\u00f1o": (),
        "Monochord": (),
        "Morchang": (),
        "Morinhoor": (),
        "Murli": (),
        "Musette": (),
        "Musical Box": (),
        "Musical bow": (),
        "Musician": (),
        "Nadaswaram": (),
        "Ney": (),
        "Noises": (),
        "Nose Flute": (),
        "Nyckelharpa": (),
        "Oboe d\u0027Amore": (),
        "Oboe": (),
        "Ocarina": (),
        "Omnichord": (),
        "Ondes Martenot": (),
        "Ophicleide": (),
        "Orchestra": (),
        "Organ": (),
        "Oud": (),
        "Outi": (),
        "Panpipes": (),
        "Parlour Grand Piano": (),
        "Pedal Steel Guitar": (),
        "Pedalboard": (),
        "Performer": (),
        "Piano Accordion": (),
        "Piano": (),
        "Piccolo Flute": (),
        "Pipa": (),
        "Pipe": (),
        "Pito": (),
        "Pixiephone": (),
        "Player Piano": (),
        "Portuguese Guitar": (),
        "Psalmodicon": (),
        "Psaltery": (),
        "Quena": (),
        "Quenacho": (),
        "Rabab": (),
        "Rauschpfeife": (),
        "Rebab": (),
        "Rebec": (),
        "Recorder": (),
        "Reeds": (),
        "Regal": (),
        "Requinto Guitar": (),
        "Resonator Guitar": (),
        "Rhaita": (),
        "Rhythm Guitar": (),
        "Rondador": (),
        "Ronroco": (),
        "Rozhok": (),
        "Ruan": (),
        "Ryuteki": (),
        "Sackbut": (),
        "Sampler": (),
        "Sampona": (),
        "Santoor": (),
        "Sanxian": (),
        "Sarangi": (),
        "Sarod": (),
        "Sarrusophone": (),
        "Saw": (),
        "Saxello": (),
        "Saxophone": (),
        "Scratches": (),
        "Semi-Acoustic Guitar": (),
        "Serpent": (),
        "Shahi Baaja": (),
        "Shakuhachi": (),
        "Shamisen": (),
        "Shanai": (),
        "Shawm": (),
        "Shenai": (),
        "Sheng": (),
        "Shinobue": (),
        "Sho": (),
        "Sintir": (),
        "Siren": (),
        "Sitar": (),
        "Slide Guitar": (),
        "Slide Whistle": (),
        "Soloist": (),
        "Sopilka": (),
        "Sopranino Saxophone": (),
        "Soprano Clarinet": (),
        "Soprano Saxophone": (),
        "Souna": (),
        "Sounds": (),
        "Sousaphone": (),
        "Spinet": (),
        "Sruti Box": (),
        "Steel Drums": (),
        "Steel Guitar": (),
        "Strings": (),
        "Stroh Violin": (),
        "Strumstick": (),
        "Stylophone": (),
        "Subcontrabass Saxophone": (),
        "Suling": (),
        "Suona": (),
        "Surbahar": (),
        "Svara Mandala": (),
        "Swarmandel": (),
        "Sympitar": (),
        "Synth": (),
        "SynthAxe": (),
        "Synthesizer": (),
        "T\u00e1rogat\u00f3": (),
        "Talkbox": (),
        "Tambura": (),
        "Tamburitza": (),
        "Tapboard": (),
        "Tape": (),
        "Tar (lute)": (),
        "Tenor Saxophone": (),
        "Theorbo": (),
        "Theremin": (),
        "Thumb Piano": (),
        "Ti-tse": (),
        "Tin Whistle": (),
        "Tiple": (),
        "Tipple": (),
        "Tonkori": (),
        "Toy Piano": (),
        "Toy": (),
        "Trautonium": (),
        "Tres": (),
        "Trombone": (),
        "Trumpet": (),
        "Tuba": (),
        "Turntables": (),
        "Twelve-String Guitar": (),
        "Ukulele": (),
        "Upright Piano": (),
        "Utogardon": (),
        "Valiha": (),
        "Valve Trombone": (),
        "Veena": (),
        "Vibraphone": (),
        "Vielle": (),
        "Vihuela": (),
        "Viol": (),
        "Viola d\u0027Amore": (),
        "Viola": (),
        "Violin": (),
        "Violone": (),
        "Virginal": (),
        "Vocoder": (),
        "Waterphone": (),
        "Whistle": (),
        "Whistling Water Jar": (),
        "Wind Chimes": (),
        "Wind": (),
        "Wobble Board": (),
        "Woodwind": (),
        "Xalam": (),
        "Xylophone": (),
        "Yang T\u0027Chin": (),
        "Yangqin": (),
        "Yorgaphone": (),
        "Zhaleika": (),
        "Zither": (),
        "Zongora": (),
        "Zukra": (),
        "Zurna": (),
        "\u0110\u00e0n b\u1ea7u": (),

        }

    ### MONGOENGINE FIELDS ###

    name = mongoengine.StringField()
    detail = mongoengine.StringField()

    ### PUBLIC METHODS ###

    @classmethod
    def from_element(cls, element):
        artist_roles = []
        if element is None or not element.text:
            return artist_roles
        current_text = ''
        bracket_depth = 0
        for character in element.text:
            if character == '[':
                bracket_depth += 1
            elif character == ']':
                bracket_depth -= 1
            elif not bracket_depth and character == ',':
                current_text = current_text.strip()
                if current_text:
                    artist_roles.append(cls.from_text(current_text))
                current_text = ''
                continue
            current_text += character
        current_text = current_text.strip()
        if current_text:
            artist_roles.append(cls.from_text(current_text))
        return artist_roles

    @classmethod
    def from_text(cls, text):
        name = ''
        current_buffer = ''
        details = []
        had_detail = False
        bracket_depth = 0
        for character in text:
            if character == '[':
                bracket_depth += 1
                if bracket_depth == 1 and not had_detail:
                    name = current_buffer
                    current_buffer = ''
                    had_detail = True
                elif 1 < bracket_depth:
                    current_buffer += character
            elif character == ']':
                bracket_depth -= 1
                if not bracket_depth:
                    details.append(current_buffer)
                    current_buffer = ''
                else:
                    current_buffer += character
            else:
                current_buffer += character
        if current_buffer and not had_detail:
            name = current_buffer
        name = name.strip()
        detail = ', '.join(_.strip() for _ in details)
        detail = detail or None
        return cls(name=name, detail=detail)