from abjad.tools import datastructuretools
import mongoengine
import re
from discograph.models.Model import Model


class ArtistRole(Model, mongoengine.EmbeddedDocument):

    ### CLASS VARIABLES ###

    class Category(datastructuretools.Enumeration):
        ACTING_LITERARY_AND_SPOKEN = 1
        CONDUCTING_AND_LEADING = 2
        DJ_MIX = 3
        FEATURING_AND_PRESENTING = 4
        INSTRUMENTS = 5
        MANAGEMENT = 6
        PRODUCTION = 7
        RELATION = 13
        REMIX = 8
        TECHNICAL = 9
        VISUAL = 10
        VOCAL = 11
        WRITING_AND_ARRANGEMENT = 12

    class Subcategory(datastructuretools.Enumeration):
        DRUMS_AND_PERCUSSION = 1
        KEYBOARD = 2
        OTHER_MUSICAL = 3
        STRINGED_INSTRUMENTS = 4
        TECHNICAL_MUSICAL = 5
        TUNED_PERCUSSION = 6
        WIND_INSTRUMENTS = 7

    _bracket_pattern = re.compile('\[(.+?)\]')

    _available_credit_roles = {

        "Alias": (Category.RELATION,),
        "Member Of": (Category.RELATION,),
        "Released On": (Category.RELATION,),
        "Sublabel Of": (Category.RELATION,),
        "Split With": (Category.RELATION,),
        "Collaborated With": (Category.RELATION,),

        "Artwork By": None,
        "Executive Producer": None,
        "Other": None,
        "Photography": None,
        "Written By": None,

        "Adapted By": (Category.WRITING_AND_ARRANGEMENT,),
        "Arranged By": (Category.WRITING_AND_ARRANGEMENT,),
        "Cadenza": (Category.WRITING_AND_ARRANGEMENT,),
        "Composed By": (Category.WRITING_AND_ARRANGEMENT,),
        "Concept By": (Category.WRITING_AND_ARRANGEMENT,),
        "Copyist": (Category.WRITING_AND_ARRANGEMENT,),
        "Instrumentation By": (Category.WRITING_AND_ARRANGEMENT,),
        "Libretto By": (Category.WRITING_AND_ARRANGEMENT,),
        "Lyrics By": (Category.WRITING_AND_ARRANGEMENT,),
        "Music By": (Category.WRITING_AND_ARRANGEMENT,),
        "Music Consultant": (Category.WRITING_AND_ARRANGEMENT,),
        "Musical Assistance": (Category.WRITING_AND_ARRANGEMENT,),
        "Orchestrated By": (Category.WRITING_AND_ARRANGEMENT,),
        "Programmed By": (Category.WRITING_AND_ARRANGEMENT,),
        "Score Editor": (Category.WRITING_AND_ARRANGEMENT,),
        "Score": (Category.WRITING_AND_ARRANGEMENT,),
        "Sequenced By": (Category.WRITING_AND_ARRANGEMENT,),
        "Songwriter": (Category.WRITING_AND_ARRANGEMENT,),
        "Sound Designer": (Category.WRITING_AND_ARRANGEMENT,),
        "Transcription By": (Category.WRITING_AND_ARRANGEMENT,),
        "Translated By": (Category.WRITING_AND_ARRANGEMENT,),
        "Words By": (Category.WRITING_AND_ARRANGEMENT,),
        "Written-By": (Category.WRITING_AND_ARRANGEMENT,),

        "Featuring": (Category.FEATURING_AND_PRESENTING),
        "Hosted By": (Category.FEATURING_AND_PRESENTING,),
        "Presenter": (Category.FEATURING_AND_PRESENTING,),

        "Chorus Master": (Category.CONDUCTING_AND_LEADING,),
        "Concertmaster": (Category.CONDUCTING_AND_LEADING,),
        "Concertmistress": (Category.CONDUCTING_AND_LEADING,),
        "Conductor": (Category.CONDUCTING_AND_LEADING,),
        "Contractor": (Category.CONDUCTING_AND_LEADING,),
        "Directed By": (Category.CONDUCTING_AND_LEADING,),
        "Leader": (Category.CONDUCTING_AND_LEADING,),
        "Repetiteur": (Category.CONDUCTING_AND_LEADING,),

        "Co-producer": (Category.PRODUCTION,),
        "Commissioned By": (Category.PRODUCTION,),
        "Compilation Producer": (Category.PRODUCTION,),
        "Compiled By": (Category.PRODUCTION,),
        "Curated By": (Category.PRODUCTION,),
        "Executive-Producer": (Category.PRODUCTION,),
        "Producer": (Category.PRODUCTION,),
        "Recording Supervisor": (Category.PRODUCTION,),
        "Reissue Producer": (Category.PRODUCTION,),
        "Research": (Category.PRODUCTION,),
        "Supervised By": (Category.PRODUCTION,),

        "Remix": (Category.REMIX,),

        "DJ Mix": (Category.DJ_MIX,),

        "Animation": (Category.VISUAL,),
        "Art Direction": (Category.VISUAL,),
        "Artwork": (Category.VISUAL,),
        "Assemblage": (Category.VISUAL,),
        "CGI Artist": (Category.VISUAL,),
        "Cameraman": (Category.VISUAL,),
        "Cinematographer": (Category.VISUAL,),
        "Cover": (Category.VISUAL,),
        "Creative Director": (Category.VISUAL,),
        "Design Concept": (Category.VISUAL,),
        "Design": (Category.VISUAL,),
        "Director Of Photography": (Category.VISUAL,),
        "Film Director": (Category.VISUAL,),
        "Film Editor": (Category.VISUAL,),
        "Film Producer": (Category.VISUAL,),
        "Film Technician": (Category.VISUAL,),
        "Gaffer": (Category.VISUAL,),
        "Graphics": (Category.VISUAL,),
        "Grip": (Category.VISUAL,),
        "Illustration": (Category.VISUAL,),
        "Layout": (Category.VISUAL,),
        "Lighting Director": (Category.VISUAL,),
        "Lighting": (Category.VISUAL,),
        "Painting": (Category.VISUAL,),
        "Photography By": (Category.VISUAL,),
        "Production Manager": (Category.VISUAL,),
        "Realization": (Category.VISUAL,),
        "Set Designer": (Category.VISUAL,),
        "Sleeve": (Category.VISUAL,),
        "Stage Manager": (Category.VISUAL,),
        "Typography": (Category.VISUAL,),
        "VJ": (Category.VISUAL,),
        "Video Editor": (Category.VISUAL,),

        "Abridged By": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Adapted By (Text)": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Choreography": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewee": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Interviewer": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Liner Notes": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Music Librarian": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Narrator": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Read By": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Screenwriter": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Script By": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Sleeve Notes": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Text By": (Category.ACTING_LITERARY_AND_SPOKEN,),
        "Voice Actor": (Category.ACTING_LITERARY_AND_SPOKEN,),

        "A\u0026R": (Category.MANAGEMENT,),
        "Administrator": (Category.MANAGEMENT,),
        "Advisor": (Category.MANAGEMENT,),
        "Booking": (Category.MANAGEMENT,),
        "Coordinator": (Category.MANAGEMENT,),
        "Legal": (Category.MANAGEMENT,),
        "Management": (Category.MANAGEMENT,),
        "Product Manager": (Category.MANAGEMENT,),

        "Crew": (Category.TECHNICAL,),
        "DAW": (Category.TECHNICAL,),
        "Edited By": (Category.TECHNICAL,),
        "Engineer": (Category.TECHNICAL,),
        "Lacquer Cut By": (Category.TECHNICAL,),
        "Mastered By": (Category.TECHNICAL,),
        "Mixed By": (Category.TECHNICAL,),
        "Recorded By": (Category.TECHNICAL,),
        "Remastered By": (Category.TECHNICAL,),
        "Tape Op": (Category.TECHNICAL,),
        "Technician": (Category.TECHNICAL,),
        "Tracking By": (Category.TECHNICAL,),
        "Transferred By": (Category.TECHNICAL,),

        "Alto Vocals": (Category.VOCAL,),
        "Backing Vocals": (Category.VOCAL,),
        "Baritone Vocals": (Category.VOCAL,),
        "Bass Vocals": (Category.VOCAL,),
        "Caller": (Category.VOCAL,),
        "Choir": (Category.VOCAL,),
        "Chorus": (Category.VOCAL,),
        "Contralto Vocals": (Category.VOCAL,),
        "Coro": (Category.VOCAL,),
        "Countertenor Vocals": (Category.VOCAL,),
        "Harmony Vocals": (Category.VOCAL,),
        "Human Beatbox": (Category.VOCAL,),
        "Humming": (Category.VOCAL,),
        "Kakegoe": (Category.VOCAL,),
        "Lead Vocals": (Category.VOCAL,),
        "MC": (Category.VOCAL,),
        "Mezzo-soprano Vocals": (Category.VOCAL,),
        "Overtone Voice": (Category.VOCAL,),
        "Rap": (Category.VOCAL,),
        "Scat": (Category.VOCAL,),
        "Solo Vocal": (Category.VOCAL,),
        "Soprano Vocals": (Category.VOCAL,),
        "Speech": (Category.VOCAL,),
        "Tenor Vocals": (Category.VOCAL,),
        "Toasting": (Category.VOCAL,),
        "Treble Vocals": (Category.VOCAL,),
        "Vocalese": (Category.VOCAL,),
        "Vocals": (Category.VOCAL,),
        "Voice": (Category.VOCAL,),
        "Whistling": (Category.VOCAL,),
        "Yodeling": (Category.VOCAL,),

        "Afox\u00e9": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Agog\u00f4": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ashiko": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bapang": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bass Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bata": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bell Tree": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bells": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bendir": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bodhr\u00e1n": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Body Percussion": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bombo": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bones": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Bongos": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Buhay": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Buk": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Cabasa": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Caixa": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Caj\u00f3n": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Calabash": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Castanets": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Caxixi": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Chak\u0027chas": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ching": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Claves": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Congas": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Cowbell": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Cuica": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Cymbal": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Daf": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Davul": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Dhol": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Dholak": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Djembe": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Drum Programming": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Drums": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Dunun": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Electronic Drums": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Finger Cymbals": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Finger Snaps": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Frame Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Friction Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ganz\u00e1": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ghatam": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ghungroo": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Goblet Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Gong": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Guiro": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Handclaps": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Hihat": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Idiophone": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Janggu": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "K\u0027kwaengwari": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Kanjira": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Karkabas": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Khartal": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Khurdak": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Lion\u0027s Roar": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Maracas": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Monkey stick": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Mridangam": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Pandeiro": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Percussion": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Rainstick": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Ratchet": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Rattle": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Reco-reco": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Repinique": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Rototoms": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Scraper": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Shaker": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Shekere": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Singing Bowls": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Skratjie": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Slapstick": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Slit Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Snare": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Spoons": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Surdo": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "T\u00fcng\u00fcr": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tabla": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Taiko": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Talking Drum": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tam-tam": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tambora": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tamborim": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tambourine": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tan-Tan": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tap Dance": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tar (Drum)": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Temple Bells": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Temple Block": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Timbales": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Timpani": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Tom Tom": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Triangle": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Udu": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Vibraslap": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Washboard": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Waterphone": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),
        "Wood Block": (Category.INSTRUMENTS, Subcategory.DRUMS_AND_PERCUSSION),

        "Amadinda": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Angklung": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Angklung": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Balafon": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Boomwhacker": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Carillon": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Celesta": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Chimes": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Crotales": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Glockenspiel": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Kalimba": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Marimba": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Marimbula": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Metallophone": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Musical Box": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Steel Drums": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Thumb Piano": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Vibraphone": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),
        "Xylophone": (Category.INSTRUMENTS, Subcategory.TUNED_PERCUSSION),

        "Baby Grand Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Chamberlin": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Concert Grand Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Dulcitone": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Electric Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Fortepiano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Grand Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Harmonium": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Harpsichord": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Keyboards": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Mellotron": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Melodica": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Omnichord": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Ondes Martenot": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Organ": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Parlour Grand Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Pedalboard": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Player Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Regal": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Stylophone": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Synth": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Synthesizer": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Toy Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Upright Piano": (Category.INSTRUMENTS, Subcategory.KEYBOARD),
        "Virginal": (Category.INSTRUMENTS, Subcategory.KEYBOARD),

        "Acoustic Bass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Acoustic Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Arco Bass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Arpa": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Autoharp": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Baglama": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bajo Quinto": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bajo Sexto": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Balalaika": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bandura": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bandurria": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Banhu": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Banjo": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Baritone Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bass Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Berimbau": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bhapang": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Biwa": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Blaster Beam": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bouzouki": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Bulbul Tarang": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Byzaanchi": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "C\u00fcmb\u00fc\u015f": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cavaquinho": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cello": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Chanzy": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Chapman Stick": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Charango": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Chitarrone": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cimbalom": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cittern": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Classical Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Clavichord": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Clavinet": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cobza": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Contrabass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Cuatro": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Dilruba": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Domra": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Doshpuluur": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Double Bass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Dulcimer": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Dutar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Ehru": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Ektare": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Electric Bass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Electric Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Electric Upright Bass": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Erhu": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Esraj": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Fiddle": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Flamenco Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Gadulka": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Gaohu": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Gayageum": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Geomungo": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Gottuv\u00e2dyam": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guimbri": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guitalele": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guitar Synthesizer": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "GuitarViol": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guitarr\u00f3n": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guqin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Gusli": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Guzheng": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Halldorophone": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Hardingfele": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Harp Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Harp": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Hummel": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Huqin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Hurdy Gurdy": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Igil": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Jarana": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Jinghu": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Jouhikko": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kabosy": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kamancha": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kantele": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kanun": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kemenche": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kobyz": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kokyu": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Kora": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Koto": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "La\u00fad": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Lap Steel Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Lead Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Liuqin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Lute": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Lyre": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Mandocello": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Mandoguitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Mandola": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Mandolin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Mandolincello": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Monochord": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Morinhoor": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Musical bow": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Nyckelharpa": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Oud": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Outi": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Pedal Steel Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Pipa": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Portuguese Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Psalmodicon": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Psaltery": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Rabab": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Rebab": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Rebec": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Requinto Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Resonator Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Rhythm Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Roncoco": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Ruan": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Santoor": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sanxian": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sarangi": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sarod": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Semi-Acoustic Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Shahi Baaja": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Shamisen": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sintir": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Slide Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Spinet": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Steel Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Strings": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Stroh Violin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Strumstick": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Surbahar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Svara Mandala": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Swarmandel": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Sympitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "SynthAxe": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tambura": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tamburitza": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tapboard": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tar (lute)": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Theorbo": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tiple": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tipple": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tonkori": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Tres": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Twelve-String Guitar": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Ukulele": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Utogardon": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Valiha": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Veena": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Vielle": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Vihuela": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Viol": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Viola d\u0027Amore": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Viola": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Violin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Violone": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Xalam": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Yang T\u0027Chin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Yangqin": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Zither": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Zongora": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "\u0110\u00e0n b\u1ea7u": (Category.INSTRUMENTS, Subcategory.STRINGED_INSTRUMENTS),
        "Accordion": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Algoza": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Alphorn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Alto Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Alto Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Alto Recorder": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Alto Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Apito": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bagpipes": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bandoneon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bansuri": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Baritone Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Barrel Organ": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bass Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bass Harmonica": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bass Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bass Tuba": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Basset Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bassoon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bayan": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bellowphone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Beresta": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Blues Harp": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bombarde": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Brass Bass": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Brass": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bucium": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Bugle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Chalumeau": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Chanter": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Chirimia": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Clarion": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Claviola": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Concert Flute": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Concertina": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Conch": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Contra-Alto Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Contrabass Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Contrabass Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Contrabassoon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Cor Anglais": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Cornet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Cornett": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Crumhorn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Daegeum": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Didgeridoo": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Dili Tuiduk": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Dizi": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Drone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Duduk": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Dulcian": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Dulzaina": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Electronic Valve Instrument": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Electronic Wind Instrument": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "English Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Euphonium": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Fife": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Flageolet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Flugabone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Flugelhorn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Fluier": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Flute": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "French Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Gemshorn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Harmonica": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Heckelphone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Helicon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Horagai": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Horns": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Hunting Horn": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Jug": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Kaval": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Kazoo": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Khene": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Launeddas": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Low Whistle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Low Whistle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Lur": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Lur": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Lyricon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Lyricon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Mellophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Melodeon": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Mizmar": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Mizwad": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Moce\u00f1o": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Murli": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Musette": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Nadaswaram": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Ney": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Nose Flute": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Oboe d\u0027Amore": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Oboe": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Ocarina": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Ophicleide": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Panpipes": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Piano Accordion": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Piccolo Flute": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Pipe": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Pito": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Pixiephone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Quena": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Quenacho": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Rauschpfeife": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Recorder": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Reeds": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Rhaita": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Rondador": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Rozhok": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Ryuteki": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sackbut": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sampona": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sarrusophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Saxello": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Serpent": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Shakuhachi": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Shanai": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Shawm": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Shenai": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sheng": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Shinobue": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sho": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Slide Whistle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sopilka": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sopranino Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Soprano Clarinet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Soprano Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Souna": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sousaphone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Sruti Box": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Subcontrabass Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Suling": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Suona": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "T\u00e1rogat\u00f3": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Tenor Saxophone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Ti-tse": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Tin Whistle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Trombone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Trumpet": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Tuba": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Valve Trombone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Whistle": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Whistling Water Jar": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Wind": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Woodwind": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Yorgaphone": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Zhaleika": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Zukra": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),
        "Zurna": (Category.INSTRUMENTS, Subcategory.WIND_INSTRUMENTS),

        "Computer": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Drum Machine": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Effects": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Electronics": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Groovebox": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Loops": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "MIDI Controller": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Noises": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Sampler": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Scratches": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Talkbox": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Tape": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Theremin": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Turntables": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),
        "Vocoder": (Category.INSTRUMENTS, Subcategory.TECHNICAL_MUSICAL),

        "Accompanied By": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Audio Generator": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Backing Band": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Band": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Bass": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Brass Band": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Bullroarer": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Concert Band": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "E-Bow": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Ensemble": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Gamelan": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Glass Harmonica": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Guest": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Homus": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Instruments": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Jew\u0027s Harp": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Mbira": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Morchang": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Musician": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Orchestra": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Performer": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Saw": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Siren": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Soloist": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Sounds": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Toy": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Trautonium": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Wind Chimes": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),
        "Wobble Board": (Category.INSTRUMENTS, Subcategory.OTHER_MUSICAL),

        }

    ### MONGOENGINE FIELDS ###

    name = mongoengine.StringField()
    detail = mongoengine.StringField()

    ### PUBLIC METHODS ###

    @classmethod
    def from_element(cls, element):
        artist_roles = []
        if element is None or not element.text:
            return artist_roles
        current_text = ''
        bracket_depth = 0
        for character in element.text:
            if character == '[':
                bracket_depth += 1
            elif character == ']':
                bracket_depth -= 1
            elif not bracket_depth and character == ',':
                current_text = current_text.strip()
                if current_text:
                    artist_roles.append(cls.from_text(current_text))
                current_text = ''
                continue
            current_text += character
        current_text = current_text.strip()
        if current_text:
            artist_roles.append(cls.from_text(current_text))
        return artist_roles

    @classmethod
    def from_text(cls, text):
        name = ''
        current_buffer = ''
        details = []
        had_detail = False
        bracket_depth = 0
        for character in text:
            if character == '[':
                bracket_depth += 1
                if bracket_depth == 1 and not had_detail:
                    name = current_buffer
                    current_buffer = ''
                    had_detail = True
                elif 1 < bracket_depth:
                    current_buffer += character
            elif character == ']':
                bracket_depth -= 1
                if not bracket_depth:
                    details.append(current_buffer)
                    current_buffer = ''
                else:
                    current_buffer += character
            else:
                current_buffer += character
        if current_buffer and not had_detail:
            name = current_buffer
        name = name.strip()
        detail = ', '.join(_.strip() for _ in details)
        detail = detail or None
        return cls(name=name, detail=detail)